---
title: "Basics"
author: "Valerio Villani"
date: "30/03/2021"
output: html_document
---

```{r setup, include=FALSE, warning=FALSE, error=FALSE}

knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(tidymodels)

theme_set(theme_bw())

```

# The Ames housing data

## Goal

Predict the sale price of a house based on its other characteristics.

```{r echo=FALSE, include=FALSE}

data(ames, package = "modeldata")

ames <- janitor::clean_names(ames)

glimpse(ames)

```

## EDA

```{r echo=FALSE}

ames %>% 
  ggplot(aes(x = sale_price)) +
  geom_histogram(bins = 50) +
  # visualise log-transformed data
  scale_x_log10()


```
```{r include=FALSE}

# apply log-transform to sale_price
ames <- ames %>% mutate(sale_price = log10(sale_price))

```


# Spending our data

The *data spending* stage is where we decide the proportion of our **train/test split**.

## Common methods for splitting data

```{r}

set.seed(123)

# calculate quantiles
qtls <- quantile(ames$sale_price, 
                 probs = c(0.25, 0.50, 0.75))

# visualise quantiles for stratified sampling
ames %>% 
  ggplot(aes(x = sale_price)) +
  geom_density() +
  geom_vline(xintercept = qtls, linetype = "dashed" ) +
  labs(x = "Sale price (log-10 USD)")



# split data into 80% train and 20% test
ames_split <- initial_split(ames, prop = 0.80,
                            # sample according to quartiles
                            strata = sale_price)

# get the train data
ames_train <- training(ames_split)

# get the test data
ames_test <- testing(ames_split)

```
